#!/usr/bin/env python3
"""Copy generated .webp animations into the frontend and write a typed index that
maps each procedural id -> { src, poster } using static imports (bundler-friendly).

Run after generate.py:
    python sync_frontend.py

This writes:
    src/prototype/cookingAnimations/generated/*.webp
    src/prototype/cookingAnimations/generated/index.ts
"""

from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).parent
DIST = ROOT / "dist"
FRONT = ROOT.parent.parent / "src" / "prototype" / "cookingAnimations" / "generated"


def ident(anim_id: str) -> str:
    return "a_" + anim_id.replace("-", "_")


def main() -> None:
    FRONT.mkdir(parents=True, exist_ok=True)

    # Clear out stale webp (keep index.ts until we rewrite it).
    for old in FRONT.glob("*.webp"):
        old.unlink()

    anim_files = sorted(p for p in DIST.glob("*.webp") if not p.name.endswith(".poster.webp"))
    ids = [p.stem for p in anim_files]

    imports: list[str] = []
    entries: list[str] = []
    for anim_id in ids:
        shutil.copy2(DIST / f"{anim_id}.webp", FRONT / f"{anim_id}.webp")
        poster = DIST / f"{anim_id}.poster.webp"
        var = ident(anim_id)
        imports.append(f'import {var}_src from "./{anim_id}.webp";')
        if poster.exists():
            shutil.copy2(poster, FRONT / f"{anim_id}.poster.webp")
            imports.append(f'import {var}_poster from "./{anim_id}.poster.webp";')
            entries.append(f'  "{anim_id}": {{ src: {var}_src, poster: {var}_poster }},')
        else:
            entries.append(f'  "{anim_id}": {{ src: {var}_src, poster: {var}_src }},')

    body = "\n".join(imports)
    table = "\n".join(entries)
    out = (
        "// AUTO-GENERATED by tools/cooking-anim/sync_frontend.py — do not edit by hand.\n"
        "// Maps procedural animation ids (see classifyStep.ts) to bundled WebP assets.\n\n"
        "export type GeneratedAnimation = { src: string; poster: string };\n\n"
        f"{body}\n\n"
        "export const ANIMATIONS: Record<string, GeneratedAnimation> = {\n"
        f"{table}\n"
        "};\n"
    )
    (FRONT / "index.ts").write_text(out)
    print(f"Synced {len(ids)} animations -> {FRONT}")
    if ids:
        print("ids:", ", ".join(ids))


if __name__ == "__main__":
    main()
