#!/usr/bin/env bun
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { canonicalConstraints, deadlineBootstrap, prototypeMeta } from "../src/data/seededScenario";
import { seededMeals } from "../src/data/seededMeals";
import { seedMeals as activePrototypeMeals } from "../src/prototype/data";

// Canonical recipe content lives in Firestore (issue #123). Reviews are stored
// in Firestore only and never embedded here, so strip them — and the derived
// `rating` — from the seed payload. `rating` is recomputed from live reviews.
const prototypeRecipes = activePrototypeMeals.map(({ reviews, rating, ...recipe }) => {
  void reviews;
  void rating;
  return recipe;
});

const outdir = path.join(process.cwd(), "functions", "src", "generated");
const outfile = path.join(outdir, "prototypeData.ts");

const banner = `// Generated by scripts/export-firebase-prototype-data.ts.
// Do not edit this file directly.

`;

const content = `${banner}export const seededMeals = ${JSON.stringify(seededMeals, null, 2)} as const;

export const prototypeRecipes = ${JSON.stringify(prototypeRecipes, null, 2)} as const;

export const canonicalConstraints = ${JSON.stringify(canonicalConstraints, null, 2)} as const;

export const prototypeMeta = ${JSON.stringify(prototypeMeta, null, 2)} as const;

export const deadlineBootstrap = ${JSON.stringify(deadlineBootstrap, null, 2)} as const;
`;

await mkdir(outdir, { recursive: true });
await writeFile(outfile, content);
console.log(`Wrote ${path.relative(process.cwd(), outfile)}`);
