#!/usr/bin/env bun
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { canonicalConstraints, deadlineBootstrap, prototypeMeta } from "../src/data/seededScenario";
import { seededMeals } from "../src/data/seededMeals";

const outdir = path.join(process.cwd(), "functions", "src", "generated");
const outfile = path.join(outdir, "prototypeData.ts");

const banner = `// Generated by scripts/export-firebase-prototype-data.ts.
// Do not edit this file directly.

`;

const content = `${banner}export const seededMeals = ${JSON.stringify(seededMeals, null, 2)} as const;

export const canonicalConstraints = ${JSON.stringify(canonicalConstraints, null, 2)} as const;

export const prototypeMeta = ${JSON.stringify(prototypeMeta, null, 2)} as const;

export const deadlineBootstrap = ${JSON.stringify(deadlineBootstrap, null, 2)} as const;
`;

await mkdir(outdir, { recursive: true });
await writeFile(outfile, content);
console.log(`Wrote ${path.relative(process.cwd(), outfile)}`);
