#!/usr/bin/env bun
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { canonicalConstraints, deadlineBootstrap, productMeta } from "../src/data/seededScenario";

// Canonical recipe content lives in Firestore/Postgres now. The generated app
// data keeps non-recipe bootstrap settings only, so deploying functions cannot
// reintroduce bundled recipe rows.
const deadlineBootstrapWithoutMeals = {
  ...deadlineBootstrap,
  meals: [],
};

const outdir = path.join(process.cwd(), "functions", "src", "generated");
const outfile = path.join(outdir, "appData.ts");

const banner = `// Generated by scripts/export-firebase-app-data.ts.
// Do not edit this file directly.

`;

const content = `${banner}export type GeneratedAppRecipe = {
  id: string;
  name: string;
  type: string;
  mealSlots: string[];
  time: number;
  price: number;
  tags: string[];
  ingredients: { name: string; quantity?: number; unit?: string; preparation?: string }[];
  allergens: string[];
  nutrition?: { calories: number; protein: number; carbs: number; fat: number };
  servings?: number;
  instructions?: string[];
  source?: string;
  note?: string;
  image?: string;
};

export const appRecipes = [] as GeneratedAppRecipe[];

export const canonicalConstraints = ${JSON.stringify(canonicalConstraints, null, 2)} as const;

export const productMeta = ${JSON.stringify(productMeta, null, 2)} as const;

export const deadlineBootstrap = ${JSON.stringify(deadlineBootstrapWithoutMeals, null, 2)} as const;
`;

await mkdir(outdir, { recursive: true });
await writeFile(outfile, content);
console.log(`Wrote ${path.relative(process.cwd(), outfile)}`);
